version: '3.7'

services:
  db:
    image: mysql
    container_name: "mysql"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - book-store-net
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "longphu"
      # OR if you want to use "root" as the user, just these two lines
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_DATABASE: ${DATABASE_NAME}

    # we mount a data volume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "book-store"
    networks:
      - book-store-net
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/

networks:
  book-store-net:
volumes:
  mysql_data: